name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # env: 
      #   NEXT_PUBLIC_CONVEX_URL: ${{ vars.NEXT_PUBLIC_CONVEX_URL }}
      #   NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    - name: Check variables
      run: |
        echo "environment: ${{ vars.ENVIRONMENT_STAGE }}"
        echo "convex variable : ${{ vars.NEXT_PUBLIC_CONVEX_URL }}"
        echo "clerk variable : ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
    - name: Build the Docker image
      run: docker build . --build-arg NEXT_PUBLIC_CONVEX_URL=${{ vars.NEXT_PUBLIC_CONVEX_URL }} --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} --file Dockerfile --tag aionair:$(date +%s)
