name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Display Environment Variables
      run: |
        echo "Convex var: $NEXT_PUBLIC_CONVEX_URL"
        echo "Clerk var: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
        echo "Convex deployment: $CONVEX_DEPLOYMENT"
      env: 
        NEXT_PUBLIC_CONVEX_URL: ${{ vars.NEXT_PUBLIC_CONVEX_URL }}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
    - name: Create .env file
      run: |
         touch .env
         echo NEXT_PUBLIC_CONVEX_URL=${{ vars.NEXT_PUBLIC_CONVEX_URL }} >> .env
         echo NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} >> .env
         echo CONVEX_DEPLOYMENT=${{ secrets.CONVEX_DEPLOYMENT }} >> .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
